package rag

import (
	"fmt"
	"strings"

	domain "github.com/shawns-yao/shawn-blog/server/internal/domain/rag"
	"github.com/yuin/goldmark/ast"
)

func byteOffset(source string, runes int) int {
	for offset := range source {
		if runes == 0 {
			return offset
		}
		runes--
	}
	return len(source)
}

func tokenPrefixBytes(source string, limit int) int {
	if CountTokens(source) <= limit {
		return len(source)
	}
	boundaries := []int{0}
	for offset := range source {
		if offset > 0 {
			boundaries = append(boundaries, offset)
		}
	}
	boundaries = append(boundaries, len(source))
	low, high := 1, len(boundaries)-1
	for low < high {
		mid := (low + high + 1) / 2
		if CountTokens(source[:boundaries[mid]]) <= limit {
			low = mid
		} else {
			high = mid - 1
		}
	}
	return boundaries[low]
}

func nodeRange(node ast.Node, source string) (int, int) {
	start, end := len(source), 0
	_ = ast.Walk(node, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if entering && n.Type() == ast.TypeBlock {
			for i := 0; i < n.Lines().Len(); i++ {
				line := n.Lines().At(i)
				start, end = min(start, line.Start), max(end, line.Stop)
			}
		}
		return ast.WalkContinue, nil
	})
	if end == 0 {
		return -1, 0
	}
	for start > 0 && source[start-1] != '\n' {
		start--
	}
	for end < len(source) && source[end] != '\n' {
		end++
	}
	if end < len(source) {
		end++
	}
	return start, end
}

func attachParents(markdown string, chunks []domain.Chunk, limit int) {
	for start := 0; start < len(chunks); {
		end := start + 1
		// Parents can join sibling subsections inside the same top-level section.
		path := parentPath(chunks[start].HeadingPath)
		for end < len(chunks) && parentPath(chunks[end].HeadingPath) == path {
			content := markdown[byteOffset(markdown, chunks[start].Start):byteOffset(markdown, chunks[end].End)]
			if CountTokens(path+"\n\n"+content) > limit {
				break
			}
			end++
		}
		for i := start; i < end; i++ {
			chunks[i].ParentStart, chunks[i].ParentEnd = chunks[start].Start, chunks[end-1].End
			chunks[i].ParentID = fmt.Sprintf("parent:%d:%d", chunks[start].Start, chunks[end-1].End)
			chunks[i].ChunkID = fmt.Sprintf("child:%d", chunks[i].Seq)
			if i > 0 && chunks[i-1].ContextHeader == chunks[i].ContextHeader {
				chunks[i].PreviousID = fmt.Sprintf("child:%d", chunks[i-1].Seq)
			}
			if i+1 < len(chunks) && chunks[i+1].ContextHeader == chunks[i].ContextHeader {
				chunks[i].NextID = fmt.Sprintf("child:%d", chunks[i+1].Seq)
			}
		}
		start = end
	}
}

func parentPath(path []string) string { return strings.Join(path[:min(len(path), 2)], " > ") }

// IDs are scoped to a document and its index profile; preview IDs are local only.
func BindChunkIDs(chunks []domain.Chunk, documentID int64, profile string) {
	prefix := fmt.Sprintf("%d:%s:", documentID, profile)
	for i := range chunks {
		chunks[i].DocumentID = documentID
		chunks[i].ChunkID = prefix + chunks[i].ChunkID
		chunks[i].ParentID = prefix + chunks[i].ParentID
		if chunks[i].PreviousID != "" {
			chunks[i].PreviousID = prefix + chunks[i].PreviousID
		}
		if chunks[i].NextID != "" {
			chunks[i].NextID = prefix + chunks[i].NextID
		}
	}
}

// Expanded content is sliced from the live original, not generated by the model.
func ExpandEvidence(item domain.Evidence, source domain.Source, chunks []domain.Chunk, parent bool) domain.Evidence {
	for i, child := range chunks {
		if child.Start != item.Start || child.End != item.End {
			continue
		}
		start, end := child.Start, child.End
		if parent {
			start, end = child.ParentStart, child.ParentEnd
		} else {
			if i > 0 && child.PreviousID != "" {
				start = chunks[i-1].Start
			}
			if i+1 < len(chunks) && child.NextID != "" {
				end = chunks[i+1].End
			}
		}
		item.Content = source.Content[byteOffset(source.Content, start):byteOffset(source.Content, end)]
		item.Start, item.End, item.Expanded = start, end, start != child.Start || end != child.End
		break
	}
	item.Tokens = CountTokens(item.ContextHeader + "\n\n" + item.Content)
	return item
}

// Trusted overlaps are merged by original coordinates, preserving repeated rows.
func MergeEvidence(a, b domain.Evidence, source domain.Source, limit int) (domain.Evidence, bool) {
	if a.MomentID != b.MomentID || a.SourceHash != b.SourceHash ||
		min(a.End, b.End) < max(a.Start, b.Start) {
		return a, false
	}
	start, end := min(a.Start, b.Start), max(a.End, b.End)
	content := source.Content[byteOffset(source.Content, start):byteOffset(source.Content, end)]
	tokens := CountTokens(a.ContextHeader + "\n\n" + content)
	if tokens > limit {
		return a, false
	}
	a.Content, a.Start, a.End, a.Tokens, a.Expanded = content, start, end, tokens, true
	if a.Kind != b.Kind {
		a.Kind = "text"
	}
	return a, true
}
