-- +goose Up
-- ===========================
-- 用户与权限系统
-- ===========================

-- 用户表
CREATE TABLE IF NOT EXISTS app_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(45)  NOT NULL,
    nickname   VARCHAR(45)  NOT NULL,
    email      VARCHAR(255),
    password   VARCHAR(60),
    avatar     VARCHAR(255),
    is_active  BOOLEAN      DEFAULT TRUE,
    is_admin   BOOLEAN      DEFAULT FALSE,
    created_at TIMESTAMPTZ  DEFAULT now(),
    updated_at TIMESTAMPTZ  DEFAULT now(),
    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT uq_app_user_email    UNIQUE (email)
);

CREATE INDEX idx_app_user_created_at ON app_user (created_at);


-- ===========================
-- 文章：分类 / 标签，手记：专栏 / 话题
-- ===========================

CREATE TABLE IF NOT EXISTS article_category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(45) NOT NULL,
    short_url  VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_article_category_name      UNIQUE (name),
    CONSTRAINT uq_article_category_short_url UNIQUE (short_url)
);

CREATE TABLE IF NOT EXISTS moment_column
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(45) NOT NULL,
    short_url  VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_moment_column_name      UNIQUE (name),
    CONSTRAINT uq_moment_column_short_url UNIQUE (short_url)
);

CREATE TABLE IF NOT EXISTS tag
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(45) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_tag_name UNIQUE (name)
);

-- ===========================
-- 评论区与评论
-- ===========================

CREATE TABLE IF NOT EXISTS comment_area
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_name  VARCHAR(45) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id    BIGINT      NOT NULL,
    content    TEXT        NOT NULL,
    author_id  BIGINT,
    nick_name  VARCHAR(45),
    ip         VARCHAR(45),
    location   VARCHAR(45),
    platform   VARCHAR(45),
    browser    VARCHAR(45),
    email      VARCHAR(255),
    website    VARCHAR(255),
    is_owner   BOOLEAN     DEFAULT FALSE,
    is_friend  BOOLEAN     DEFAULT FALSE,
    is_author  BOOLEAN     DEFAULT FALSE,
    is_viewed  BOOLEAN     DEFAULT FALSE,
    is_top     BOOLEAN     DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    parent_id  BIGINT,

    FOREIGN KEY (area_id)  REFERENCES comment_area (id),
    FOREIGN KEY (parent_id) REFERENCES comment (id) ON DELETE CASCADE
    -- author_id 故意不加外键，以支持匿名 / 登录混合场景
);

CREATE INDEX idx_comment_area_created_at ON comment (area_id, created_at);
CREATE INDEX idx_comment_parent_id        ON comment (parent_id);
CREATE INDEX idx_comment_is_top           ON comment (area_id, is_top DESC, created_at DESC);

-- ===========================
-- 文章 / 状态更新 / 页面 / 一日一言 / 思考
-- ===========================

CREATE TABLE IF NOT EXISTS article
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    summary      TEXT         NOT NULL,
    ai_summary   TEXT,
    lead_in      TEXT,
    toc          JSONB        NOT NULL,
    content      TEXT         NOT NULL,
    author_id    BIGINT       NOT NULL,
    cover        VARCHAR(255),
    category_id  BIGINT,
    comment_id   BIGINT,
    short_url    VARCHAR(255) NOT NULL,
    is_published BOOLEAN      DEFAULT FALSE,
    created_at   TIMESTAMPTZ  DEFAULT now(),
    updated_at   TIMESTAMPTZ  DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    is_top       BOOLEAN      DEFAULT FALSE,
    is_hot       BOOLEAN      DEFAULT FALSE,
    is_original  BOOLEAN      DEFAULT TRUE,

    CONSTRAINT uq_article_short_url UNIQUE (short_url),

    FOREIGN KEY (author_id)   REFERENCES app_user (id),
    FOREIGN KEY (category_id) REFERENCES article_category (id),
    FOREIGN KEY (comment_id)  REFERENCES comment_area (id)
);

CREATE INDEX idx_article_published_created_at
    ON article (is_published, created_at DESC);
CREATE INDEX idx_article_short_url
    ON article (short_url);


CREATE TABLE IF NOT EXISTS article_metrics
(
    article_id BIGINT PRIMARY KEY
        REFERENCES article (id) ON DELETE CASCADE,
    views      BIGINT  NOT NULL DEFAULT 0,
    likes      INTEGER NOT NULL DEFAULT 0,
    comments   INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ      DEFAULT now()
);


CREATE TABLE IF NOT EXISTS moment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    summary      TEXT         NOT NULL,
    ai_summary   TEXT,
    content      TEXT         NOT NULL,
    author_id    BIGINT       NOT NULL,
    toc          JSONB        NOT NULL,
    img          TEXT,
    column_id    BIGINT,
    comment_id   BIGINT,
    short_url    VARCHAR(255) NOT NULL,
    is_published BOOLEAN      DEFAULT FALSE,
    created_at   TIMESTAMPTZ  DEFAULT now(),
    updated_at   TIMESTAMPTZ  DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    is_top       BOOLEAN      DEFAULT FALSE,
    is_hot       BOOLEAN      DEFAULT FALSE,
    is_original  BOOLEAN      DEFAULT TRUE,

    CONSTRAINT uq_moment_short_url UNIQUE (short_url),

    FOREIGN KEY (author_id)  REFERENCES app_user (id),
    FOREIGN KEY (column_id)  REFERENCES moment_column (id),
    FOREIGN KEY (comment_id) REFERENCES comment_area (id)
);

CREATE INDEX idx_moment_published_created_at
    ON moment (is_published, created_at DESC);


CREATE TABLE IF NOT EXISTS moment_metrics
(
    moment_id  BIGINT PRIMARY KEY
        REFERENCES moment (id) ON DELETE CASCADE,
    views      BIGINT  NOT NULL DEFAULT 0,
    likes      INTEGER NOT NULL DEFAULT 0,
    comments   INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ      DEFAULT now()
);


CREATE TABLE IF NOT EXISTS page
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    ai_summary  TEXT,
    short_url   VARCHAR(255) NOT NULL,
    is_enabled  BOOLEAN      DEFAULT TRUE,
    is_builtin  BOOLEAN      DEFAULT FALSE,
    toc         JSONB        NOT NULL,
    content     TEXT         NOT NULL,
    comment_id  BIGINT,
    created_at  TIMESTAMPTZ  DEFAULT now(),
    updated_at  TIMESTAMPTZ  DEFAULT now(),
    deleted_at  TIMESTAMPTZ,

    CONSTRAINT uq_page_short_url UNIQUE (short_url),

    FOREIGN KEY (comment_id) REFERENCES comment_area (id)
);

CREATE INDEX idx_page_short_url ON page (short_url);


CREATE TABLE IF NOT EXISTS page_metrics
(
    page_id  BIGINT PRIMARY KEY
        REFERENCES page (id) ON DELETE CASCADE,
    views      BIGINT  NOT NULL DEFAULT 0,
    likes      INTEGER NOT NULL DEFAULT 0,
    comments   INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ      DEFAULT now()
);


CREATE TABLE IF NOT EXISTS thinking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT        NOT NULL,
    author     VARCHAR(45) NOT NULL DEFAULT '原创',
    created_at TIMESTAMPTZ          DEFAULT now()
);

-- ===========================
-- 文章 / 手记 标签关联
-- ===========================

CREATE TABLE IF NOT EXISTS article_tag
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,

    FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id)     REFERENCES tag (id)     ON DELETE CASCADE,

    CONSTRAINT uq_article_tag UNIQUE (article_id, tag_id)
);

CREATE TABLE IF NOT EXISTS moment_topic
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment_id BIGINT NOT NULL,
    tag_id    BIGINT NOT NULL,

    FOREIGN KEY (moment_id) REFERENCES moment (id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id)    REFERENCES tag (id)    ON DELETE CASCADE,

    CONSTRAINT uq_moment_topic UNIQUE (moment_id, tag_id)
);

-- ===========================
-- 导航栏
-- ===========================

CREATE TABLE IF NOT EXISTS nav_menu
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(45)  NOT NULL,
    url        VARCHAR(255) NOT NULL,
    sort       INTEGER      NOT NULL,
    parent_id  BIGINT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,

    FOREIGN KEY (parent_id) REFERENCES nav_menu (id) ON DELETE CASCADE,
    CONSTRAINT uq_nav_menu_parent_sort UNIQUE (parent_id, sort)
);

-- ===========================
-- 用户社交 / 点赞（合并版）
-- ===========================

-- +goose StatementBegin
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'like_target_type') THEN
CREATE TYPE like_target_type AS ENUM ('article', 'moment', 'page');
END IF;
END
$$;
-- +goose StatementEnd

CREATE TABLE IF NOT EXISTS content_like
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type like_target_type NOT NULL,
    target_id   BIGINT           NOT NULL,
    user_id     BIGINT,
    session_id  VARCHAR(255),
    created_at  TIMESTAMPTZ      DEFAULT now(),

    -- 登录用户防重复点赞
    CONSTRAINT uq_content_like_user
        UNIQUE (target_type, target_id, user_id),

    -- 未登录用户（session）防重复点赞
    CONSTRAINT uq_content_like_session
        UNIQUE (target_type, target_id, session_id)
);

CREATE INDEX idx_content_like_target
    ON content_like (target_type, target_id);

-- ===========================
-- 文件 / 配置 / 网站信息
-- ===========================

CREATE TABLE IF NOT EXISTS upload_file
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    path       VARCHAR(255) NOT NULL,
    type       VARCHAR(45)  NOT NULL,
    size       BIGINT       NOT NULL,
    created_at TIMESTAMPTZ  DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sys_config
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(45) NOT NULL,
    value      TEXT        NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT uq_sys_config_key UNIQUE (config_key)
);

CREATE TABLE IF NOT EXISTS website_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    info_key   VARCHAR(45) NOT NULL,
    value      TEXT        NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT uq_website_info_key UNIQUE (info_key)
);

-- ===========================
-- 友链 / 通知 / 管理 Token
-- ===========================

CREATE TABLE IF NOT EXISTS friend_link
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    url         VARCHAR(255) NOT NULL,
    logo        VARCHAR(255),
    description TEXT,
    rss_url     VARCHAR(255),
    user_id     BIGINT,
    is_active   BOOLEAN      DEFAULT FALSE,
    created_at  TIMESTAMPTZ  DEFAULT now(),
    updated_at  TIMESTAMPTZ  DEFAULT now(),
    deleted_at  TIMESTAMPTZ,

    FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS friend_link_applications
(
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(255),
    url         VARCHAR(255) NOT NULL,
    logo        VARCHAR(255),
    description TEXT,
    user_id     BIGINT,
    message     TEXT,
    status      VARCHAR(20)  DEFAULT 'pending',
    created_at  TIMESTAMPTZ  DEFAULT now(),
    updated_at  TIMESTAMPTZ  DEFAULT now(),

    FOREIGN KEY (user_id) REFERENCES app_user (id),

    CONSTRAINT chk_friend_link_app_status
        CHECK (status IN ('pending', 'approved', 'rejected'))
);


CREATE TABLE IF NOT EXISTS global_notification
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     TEXT        NOT NULL,
    publish_at  TIMESTAMPTZ NOT NULL,
    expire_at   TIMESTAMPTZ NOT NULL,
    allow_close BOOLEAN     DEFAULT TRUE,
    created_at  TIMESTAMPTZ DEFAULT now(),
    updated_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admin_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT       NOT NULL,
    description TEXT,
    expire_at   TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  DEFAULT now(),
    updated_at  TIMESTAMPTZ  DEFAULT now(),

    CONSTRAINT uq_admin_token_token UNIQUE (token),
    FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX idx_admin_token_user      ON admin_token (user_id);
CREATE INDEX idx_admin_token_expire_at ON admin_token (expire_at);

-- ===========================
-- OAuth2 Client
-- ===========================

CREATE TABLE IF NOT EXISTS oauth_provider
(
    id                     BIGSERIAL PRIMARY KEY,

    provider_key           VARCHAR(64)  NOT NULL UNIQUE,
    display_name           VARCHAR(128) NOT NULL,

    client_id              VARCHAR(255) NOT NULL,
    client_secret          VARCHAR(255) NOT NULL,

    authorization_endpoint VARCHAR(512) NOT NULL,
    token_endpoint         VARCHAR(512) NOT NULL,
    userinfo_endpoint      VARCHAR(512),

    redirect_uri_template  VARCHAR(512) NOT NULL,

    scopes                 VARCHAR(512)          DEFAULT '',

    issuer                 VARCHAR(512),
    jwks_uri               VARCHAR(512),
    pkce_required          BOOLEAN               DEFAULT FALSE,

    enabled                BOOLEAN               DEFAULT TRUE,

    extra_params           JSONB                 DEFAULT '{}'::jsonb,

    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_oauth
(
    id            BIGSERIAL PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,

    provider_key  VARCHAR(64)  NOT NULL,
    oauth_id      VARCHAR(255) NOT NULL,
    access_token  VARCHAR(512),
    refresh_token VARCHAR(512),
    expires_at    TIMESTAMPTZ,

    created_at    TIMESTAMPTZ  DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  DEFAULT NOW(),

    UNIQUE (user_id, provider_key),
    UNIQUE (provider_key, oauth_id),

    FOREIGN KEY (provider_key) REFERENCES oauth_provider (provider_key)
);

CREATE INDEX idx_user_oauth_user ON user_oauth (user_id);

-- ===========================
-- 页脚与相册
-- ===========================

CREATE TABLE IF NOT EXISTS footer_section
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    links      JSONB        NOT NULL,
    created_at TIMESTAMPTZ  DEFAULT now(),
    updated_at TIMESTAMPTZ  DEFAULT now()
);

CREATE TABLE IF NOT EXISTS photo
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url         VARCHAR(255) NOT NULL,
    location    VARCHAR(255),
    device      VARCHAR(255),
    shade       VARCHAR(255),
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);
-- +goose Down

DROP TABLE IF EXISTS photo;
DROP TABLE IF EXISTS footer_section;
DROP TABLE IF EXISTS user_oauth;
DROP TABLE IF EXISTS oauth_provider;
DROP TABLE IF EXISTS admin_token;
DROP TABLE IF EXISTS global_notification;
DROP TABLE IF EXISTS friend_link_applications;
DROP TABLE IF EXISTS friend_link;
DROP TABLE IF EXISTS website_info;
DROP TABLE IF EXISTS sys_config;
DROP TABLE IF EXISTS upload_file;
DROP TABLE IF EXISTS content_like;
DROP TYPE  IF EXISTS like_target_type;
DROP TABLE IF EXISTS nav_menu;
DROP TABLE IF EXISTS moment_topic;
DROP TABLE IF EXISTS article_tag;
DROP TABLE IF EXISTS thinking;
DROP TABLE IF EXISTS page_metrics;
DROP TABLE IF EXISTS page;
DROP TABLE IF EXISTS moment_metrics;
DROP TABLE IF EXISTS moment;
DROP TABLE IF EXISTS article_metrics;
DROP TABLE IF EXISTS article;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS comment_area;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS moment_column;
DROP TABLE IF EXISTS article_category;
DROP TABLE IF EXISTS app_user;
