-- +goose Up
CREATE TABLE IF NOT EXISTS webhook
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    url              VARCHAR(512) NOT NULL,
    events           JSONB        NOT NULL,
    headers          JSONB        NOT NULL,
    payload_template TEXT         NOT NULL,
    is_enabled       BOOLEAN      DEFAULT TRUE,
    created_at       TIMESTAMPTZ  DEFAULT now(),
    updated_at       TIMESTAMPTZ  DEFAULT now(),
    deleted_at       TIMESTAMPTZ
);

CREATE INDEX idx_webhook_enabled ON webhook (is_enabled);

CREATE TABLE IF NOT EXISTS webhook_history
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_id      BIGINT       NOT NULL,
    event_name      VARCHAR(128) NOT NULL,
    request_url     VARCHAR(512) NOT NULL,
    request_headers JSONB        NOT NULL,
    request_body    TEXT         NOT NULL,
    response_status INTEGER,
    response_headers JSONB       NOT NULL,
    response_body   TEXT,
    error_message   TEXT,
    is_test         BOOLEAN      DEFAULT FALSE,
    created_at      TIMESTAMPTZ  DEFAULT now(),

    FOREIGN KEY (webhook_id) REFERENCES webhook (id) ON DELETE CASCADE
);

CREATE INDEX idx_webhook_history_webhook_id ON webhook_history (webhook_id);
CREATE INDEX idx_webhook_history_created_at ON webhook_history (created_at DESC);

INSERT INTO sys_config (config_key, value)
VALUES ('webhook.timeoutSeconds', '30'),
       ('webhook.workers', '4'),
       ('webhook.queueSize', '200')
ON CONFLICT (config_key) DO NOTHING;

-- +goose Down
DELETE FROM sys_config WHERE config_key IN (
    'webhook.timeoutSeconds',
    'webhook.workers',
    'webhook.queueSize'
);

DROP TABLE IF EXISTS webhook_history;
DROP TABLE IF EXISTS webhook;
