-- +goose Up
-- ===========================
-- 联合配置 / 实例 / 缓存
-- ===========================

CREATE TABLE IF NOT EXISTS federation_config
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key   VARCHAR(45) NOT NULL,
    value        TEXT        NOT NULL,
    is_sensitive BOOLEAN     NOT NULL DEFAULT FALSE,
    group_path   TEXT,
    label        VARCHAR(100),
    description  TEXT,
    value_type   VARCHAR(20) NOT NULL DEFAULT 'string',
    enum_options JSONB       NOT NULL DEFAULT '[]'::jsonb,
    default_value TEXT,
    visible_when JSONB       NOT NULL DEFAULT '[]'::jsonb,
    sort         INT         NOT NULL DEFAULT 0,
    meta         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ DEFAULT now(),
    updated_at       TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT uq_federation_config_key UNIQUE (config_key)
);

INSERT INTO federation_config (config_key, value, is_sensitive, group_path, label, description, value_type, enum_options, default_value, visible_when, sort, meta)
VALUES
    ('federation.enabled', 'false', FALSE, 'federation/base', '启用', '是否启用联合', 'bool', '[]'::jsonb, 'false', '[]'::jsonb, 10, '{"inputType":"switch"}'::jsonb),
    ('federation.instanceName', '', FALSE, 'federation/base', '实例名称', '对外展示的实例名称', 'string', '[]'::jsonb, NULL, '[]'::jsonb, 20, '{}'::jsonb),
    ('federation.instanceURL', '', FALSE, 'federation/base', '实例地址', '对外访问的实例根地址', 'string', '[]'::jsonb, NULL, '[]'::jsonb, 30, '{}'::jsonb),
    ('federation.signatureAlg', 'rsa-sha256', FALSE, 'federation/security', '签名算法', 'HTTP Signatures 使用的算法', 'enum', '["rsa-sha256"]'::jsonb, 'rsa-sha256', '[]'::jsonb, 10, '{}'::jsonb),
    ('federation.publicKey', '', FALSE, 'federation/security', '公钥', '对外发布的公钥', 'string', '[]'::jsonb, NULL, '[]'::jsonb, 20, '{}'::jsonb),
    ('federation.privateKey', '', TRUE, 'federation/security', '私钥', '签名使用的私钥', 'string', '[]'::jsonb, NULL, '[]'::jsonb, 30, '{"inputType":"password"}'::jsonb),
    ('federation.requireHTTPS', 'true', FALSE, 'federation/security', '强制 HTTPS', '仅允许 HTTPS 实例', 'bool', '[]'::jsonb, 'true', '[]'::jsonb, 40, '{"inputType":"switch"}'::jsonb),
    ('federation.allowInbound', 'true', FALSE, 'federation/security', '允许入站', '允许其他实例请求本实例', 'bool', '[]'::jsonb, 'true', '[]'::jsonb, 50, '{"inputType":"switch"}'::jsonb),
    ('federation.allowOutbound', 'true', FALSE, 'federation/security', '允许出站', '允许本实例请求其他实例', 'bool', '[]'::jsonb, 'true', '[]'::jsonb, 60, '{"inputType":"switch"}'::jsonb),
    ('federation.defaultPolicies', '{}' , FALSE, 'federation/policies', '默认策略', '实例默认策略 JSON', 'json', '[]'::jsonb, '{}' , '[]'::jsonb, 10, '{}'::jsonb),
    ('federation.rateLimits', '{}' , FALSE, 'federation/limits', '速率限制', '速率限制 JSON', 'json', '[]'::jsonb, '{}' , '[]'::jsonb, 10, '{}'::jsonb)
ON CONFLICT (config_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS federation_instance
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_url         VARCHAR(255) NOT NULL,
    name             VARCHAR(255),
    description      TEXT,
    protocol_version VARCHAR(20),
    public_key       TEXT,
    key_id           TEXT,
    features         JSONB        NOT NULL DEFAULT '[]'::jsonb,
    policies         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    endpoints        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    status           VARCHAR(20)  NOT NULL DEFAULT 'pending',
    last_seen_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  DEFAULT now(),
    updated_at       TIMESTAMPTZ  DEFAULT now(),

    CONSTRAINT uq_federation_instance_base_url UNIQUE (base_url)
);

CREATE TABLE IF NOT EXISTS federated_post_cache
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id      BIGINT      NOT NULL,
    remote_post_id   VARCHAR(255),
    url              VARCHAR(500) NOT NULL,
    title            VARCHAR(500) NOT NULL,
    summary          TEXT         NOT NULL,
    content_preview  TEXT,
    author           JSONB        NOT NULL DEFAULT '{}'::jsonb,
    tags             JSONB        NOT NULL DEFAULT '[]'::jsonb,
    categories       JSONB        NOT NULL DEFAULT '[]'::jsonb,
    published_at     TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ,
    cover_image      VARCHAR(500),
    language         VARCHAR(20),
    allow_citation   BOOLEAN      NOT NULL DEFAULT TRUE,
    allow_comment    BOOLEAN      NOT NULL DEFAULT TRUE,
    etag             VARCHAR(255),
    last_modified    VARCHAR(255),
    cached_at        TIMESTAMPTZ  DEFAULT now(),

    CONSTRAINT fk_federated_post_instance FOREIGN KEY (instance_id) REFERENCES federation_instance (id),
    CONSTRAINT uq_federated_post_url UNIQUE (url)
);

CREATE INDEX IF NOT EXISTS idx_federated_post_instance_published
    ON federated_post_cache (instance_id, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_federated_post_instance_remote
    ON federated_post_cache (instance_id, remote_post_id);

CREATE TABLE IF NOT EXISTS federated_citation
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id   BIGINT      NOT NULL,
    source_post_url      VARCHAR(500) NOT NULL,
    source_post_title    VARCHAR(500),
    target_article_id    BIGINT       NOT NULL,
    citation_context     TEXT,
    citation_type        VARCHAR(20)  NOT NULL DEFAULT 'reference',
    status               VARCHAR(20)  NOT NULL DEFAULT 'pending',
    requested_at         TIMESTAMPTZ  DEFAULT now(),
    approved_at          TIMESTAMPTZ,
    rejected_at          TIMESTAMPTZ,
    reject_reason        TEXT,

    CONSTRAINT fk_federated_citation_instance FOREIGN KEY (source_instance_id) REFERENCES federation_instance (id),
    CONSTRAINT fk_federated_citation_article FOREIGN KEY (target_article_id) REFERENCES article (id)
);

CREATE INDEX IF NOT EXISTS idx_federated_citation_target_status
    ON federated_citation (target_article_id, status);
CREATE INDEX IF NOT EXISTS idx_federated_citation_status_created
    ON federated_citation (status, requested_at DESC);

CREATE TABLE IF NOT EXISTS federated_mention
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id  BIGINT      NOT NULL,
    source_post_url     VARCHAR(500) NOT NULL,
    source_post_title   VARCHAR(500),
    mentioned_user_id   BIGINT       NOT NULL,
    mention_context     TEXT         NOT NULL,
    mention_type        VARCHAR(20)  NOT NULL DEFAULT 'discussion',
    is_read             BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  DEFAULT now(),
    read_at             TIMESTAMPTZ,

    CONSTRAINT fk_federated_mention_instance FOREIGN KEY (source_instance_id) REFERENCES federation_instance (id),
    CONSTRAINT fk_federated_mention_user FOREIGN KEY (mentioned_user_id) REFERENCES app_user (id)
);

CREATE INDEX IF NOT EXISTS idx_federated_mention_user_read
    ON federated_mention (mentioned_user_id, is_read, created_at DESC);

-- ===========================
-- 友链扩展
-- ===========================

ALTER TABLE friend_link
    ADD COLUMN IF NOT EXISTS kind VARCHAR(20) NOT NULL DEFAULT 'manual',
    ADD COLUMN IF NOT EXISTS sync_mode VARCHAR(20) NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS instance_id BIGINT,
    ADD COLUMN IF NOT EXISTS last_sync_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS last_sync_status VARCHAR(20),
    ADD COLUMN IF NOT EXISTS sync_interval INT,
    ADD COLUMN IF NOT EXISTS total_posts_cached INT NOT NULL DEFAULT 0;

ALTER TABLE friend_link
    ADD CONSTRAINT fk_friend_link_instance
        FOREIGN KEY (instance_id) REFERENCES federation_instance (id);

ALTER TABLE friend_link_applications
    ADD COLUMN IF NOT EXISTS apply_channel VARCHAR(20) NOT NULL DEFAULT 'user',
    ADD COLUMN IF NOT EXISTS requested_sync_mode VARCHAR(20) NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS rss_url VARCHAR(255),
    ADD COLUMN IF NOT EXISTS instance_url VARCHAR(255),
    ADD COLUMN IF NOT EXISTS manifest JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS signature_key_id TEXT,
    ADD COLUMN IF NOT EXISTS signature_verified BOOLEAN NOT NULL DEFAULT FALSE;

-- +goose Down
ALTER TABLE friend_link_applications
    DROP COLUMN IF EXISTS signature_verified,
    DROP COLUMN IF EXISTS signature_key_id,
    DROP COLUMN IF EXISTS manifest,
    DROP COLUMN IF EXISTS instance_url,
    DROP COLUMN IF EXISTS rss_url,
    DROP COLUMN IF EXISTS requested_sync_mode,
    DROP COLUMN IF EXISTS apply_channel;

ALTER TABLE friend_link
    DROP CONSTRAINT IF EXISTS fk_friend_link_instance;

ALTER TABLE friend_link
    DROP COLUMN IF EXISTS total_posts_cached,
    DROP COLUMN IF EXISTS sync_interval,
    DROP COLUMN IF EXISTS last_sync_status,
    DROP COLUMN IF EXISTS last_sync_at,
    DROP COLUMN IF EXISTS instance_id,
    DROP COLUMN IF EXISTS sync_mode,
    DROP COLUMN IF EXISTS kind;

DROP TABLE IF EXISTS federated_mention;
DROP TABLE IF EXISTS federated_citation;
DROP TABLE IF EXISTS federated_post_cache;
DROP TABLE IF EXISTS federation_instance;
DROP TABLE IF EXISTS federation_config;
