-- +goose Up

CREATE TABLE IF NOT EXISTS federation_outbound_delivery
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id          VARCHAR(64)  NOT NULL,
    delivery_type       VARCHAR(20)  NOT NULL,
    source_article_id   BIGINT,
    target_instance_url VARCHAR(255) NOT NULL,
    target_endpoint     VARCHAR(500) NOT NULL,
    payload             JSONB        NOT NULL DEFAULT '{}'::jsonb,
    status              VARCHAR(20)  NOT NULL,
    attempt_count       INT          NOT NULL DEFAULT 0,
    max_attempts        INT          NOT NULL DEFAULT 6,
    next_retry_at       TIMESTAMPTZ,
    http_status         INT,
    response_body       TEXT,
    error_message       TEXT,
    remote_ticket_id    VARCHAR(128),
    trace_id            VARCHAR(64),
    last_callback_at    TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_federation_outbound_request_id UNIQUE (request_id),
    CONSTRAINT fk_federation_outbound_article FOREIGN KEY (source_article_id) REFERENCES article (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_federation_outbound_status_retry
    ON federation_outbound_delivery (status, next_retry_at);
CREATE INDEX IF NOT EXISTS idx_federation_outbound_type_created
    ON federation_outbound_delivery (delivery_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_federation_outbound_target_created
    ON federation_outbound_delivery (target_instance_url, created_at DESC);

CREATE TABLE IF NOT EXISTS admin_notification
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    notif_type   VARCHAR(50)  NOT NULL,
    title        VARCHAR(200) NOT NULL,
    content      TEXT         NOT NULL,
    payload      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    read_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_admin_notification_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admin_notification_user_read_created
    ON admin_notification (user_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_notification_type_created
    ON admin_notification (notif_type, created_at DESC);

-- +goose Down

DROP TABLE IF EXISTS admin_notification;
DROP TABLE IF EXISTS federation_outbound_delivery;
