-- +goose Up
CREATE TABLE IF NOT EXISTS activitypub_follower
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id           VARCHAR(500) NOT NULL,
    inbox_url          VARCHAR(500) NOT NULL,
    shared_inbox_url   VARCHAR(500),
    preferred_username VARCHAR(255),
    display_name       VARCHAR(255),
    status             VARCHAR(20)  NOT NULL DEFAULT 'active',
    followed_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ           DEFAULT now(),
    updated_at         TIMESTAMPTZ           DEFAULT now(),

    CONSTRAINT uq_activitypub_follower_actor UNIQUE (actor_id)
);

CREATE INDEX IF NOT EXISTS idx_activitypub_follower_status_updated
    ON activitypub_follower (status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_activitypub_follower_inbox
    ON activitypub_follower (inbox_url);

CREATE TABLE IF NOT EXISTS activitypub_outbox_item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id  VARCHAR(500) NOT NULL,
    object_id    VARCHAR(500) NOT NULL,
    source_type  VARCHAR(20)  NOT NULL,
    source_id    BIGINT       NOT NULL,
    source_url   VARCHAR(500) NOT NULL,
    summary      TEXT         NOT NULL DEFAULT '',
    activity     JSONB        NOT NULL,
    published_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at   TIMESTAMPTZ           DEFAULT now(),
    updated_at   TIMESTAMPTZ           DEFAULT now(),

    CONSTRAINT uq_activitypub_outbox_activity UNIQUE (activity_id),
    CONSTRAINT uq_activitypub_outbox_object UNIQUE (object_id)
);

CREATE INDEX IF NOT EXISTS idx_activitypub_outbox_source
    ON activitypub_outbox_item (source_type, source_id, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_activitypub_outbox_published
    ON activitypub_outbox_item (published_at DESC);

ALTER TABLE article
    ADD COLUMN IF NOT EXISTS activitypub_object_id VARCHAR(500);

ALTER TABLE article
    ADD COLUMN IF NOT EXISTS activitypub_last_published_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS uq_article_activitypub_object_id
    ON article (activitypub_object_id)
    WHERE activitypub_object_id IS NOT NULL;

ALTER TABLE comment
    ADD COLUMN IF NOT EXISTS is_federated BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE comment
    ADD COLUMN IF NOT EXISTS federated_protocol VARCHAR(20);

ALTER TABLE comment
    ADD COLUMN IF NOT EXISTS federated_actor VARCHAR(500);

ALTER TABLE comment
    ADD COLUMN IF NOT EXISTS federated_object_id VARCHAR(500);

ALTER TABLE comment
    ADD COLUMN IF NOT EXISTS allow_local_reply BOOLEAN NOT NULL DEFAULT TRUE;

CREATE INDEX IF NOT EXISTS idx_comment_federated_object_id
    ON comment (federated_object_id);

CREATE INDEX IF NOT EXISTS idx_comment_area_federated_created
    ON comment (area_id, is_federated, created_at DESC);

-- +goose Down
DROP INDEX IF EXISTS idx_comment_area_federated_created;
DROP INDEX IF EXISTS idx_comment_federated_object_id;

ALTER TABLE comment
    DROP COLUMN IF EXISTS allow_local_reply;

ALTER TABLE comment
    DROP COLUMN IF EXISTS federated_object_id;

ALTER TABLE comment
    DROP COLUMN IF EXISTS federated_actor;

ALTER TABLE comment
    DROP COLUMN IF EXISTS federated_protocol;

ALTER TABLE comment
    DROP COLUMN IF EXISTS is_federated;

DROP INDEX IF EXISTS uq_article_activitypub_object_id;

ALTER TABLE article
    DROP COLUMN IF EXISTS activitypub_last_published_at;

ALTER TABLE article
    DROP COLUMN IF EXISTS activitypub_object_id;

DROP INDEX IF EXISTS idx_activitypub_outbox_published;
DROP INDEX IF EXISTS idx_activitypub_outbox_source;
DROP TABLE IF EXISTS activitypub_outbox_item;

DROP INDEX IF EXISTS idx_activitypub_follower_inbox;
DROP INDEX IF EXISTS idx_activitypub_follower_status_updated;
DROP TABLE IF EXISTS activitypub_follower;
