-- +goose Up

-- ===========================================================================
-- D. 删除「导航菜单」
--
-- 目标：前台导航不再有数据源与后台管理页，改为 web/ 内硬编码常量
--       （web/src/lib/shared/nav/nav-items.ts 的 NAV_ITEMS）。
--   删除：nav_menu（含 0051 的种子数据）
--
-- 代码侧前置（已完成）：
--   server 删 internal/{app,domain}/navigation、navmenu handler/contract、
--          navigation_repository，以及 /api/v2/public/nav-menus、
--          /api/v2/admin/nav-menus* 路由；并移除 ISR 的 layout:nav 失效订阅。
--   admin  删 views/navigation、services/navigation.ts、constants/nav-menu-icons.ts
--          与「导航菜单」菜单项。
--   web    删 lib/features/navigation，+layout.server.ts 不再拉取导航数据，
--          +layout.svelte 改传 NAV_ITEMS 常量。
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- D1. 删除导航菜单表
--     自引用外键 nav_menu_parent_id_fkey 与唯一约束 uq_nav_menu_parent_sort
--     随表一并删除，无需单独 DROP。
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS nav_menu;


-- +goose Down

-- 本迁移不可逆：导航入口已改为代码内常量，原表数据无法还原（删除即真删）。
-- Down 仅恢复结构，不回填数据。
--
-- 说明：0051 的种子刻意不回填——其中的「文章」(/posts)、「思考」(/thinkings)
-- 指向的路由已分别由 0072、0071 删除，回填只会重新引入死链。
--
-- 结构按删除前的实际形态复现：含 0010 增加的 icon 列，以及 0053 将其改为
-- DEFERRABLE 的 uq_nav_menu_parent_sort。

CREATE TABLE IF NOT EXISTS nav_menu
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(45)  NOT NULL,
    url        VARCHAR(255) NOT NULL,
    sort       INTEGER      NOT NULL,
    parent_id  BIGINT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    icon       VARCHAR(64),

    FOREIGN KEY (parent_id) REFERENCES nav_menu (id) ON DELETE CASCADE,
    CONSTRAINT uq_nav_menu_parent_sort UNIQUE (parent_id, sort) DEFERRABLE INITIALLY IMMEDIATE
);
