-- +goose Up

-- P5 前台「书架」改造 · 第一步（只增不减）
--
-- 背景：原 moment_column（专栏）是一级扁平结构，无法承载「一级 AI → 二级 Agent/RAG」
-- 的两级文件夹体系。本迁移新建 folder 表、迁移既有专栏数据，并给 moment 加 folder_id。
--
-- 本迁移刻意不删除 moment.column_id 与 moment_column 表：新旧结构并存，
-- 待前端切换到 folder 后再由后续迁移清理，保证此步可安全回滚。

CREATE TABLE IF NOT EXISTS folder
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope      VARCHAR(32)  NOT NULL DEFAULT 'moment',
    parent_id  BIGINT,
    name       VARCHAR(64)  NOT NULL,
    short_url  VARCHAR(255),
    sort_order INT          NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ           DEFAULT now(),
    updated_at TIMESTAMPTZ           DEFAULT now(),
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_folder_parent FOREIGN KEY (parent_id) REFERENCES folder (id)
);

-- 同一 scope、同一父节点下不允许重名（含 parent_id 为 NULL 的一级文件夹）。
-- 必须用 NULLS NOT DISTINCT：PostgreSQL 默认认为 NULL != NULL，
-- 否则一级文件夹的重名不会被唯一索引拦截。需要 PostgreSQL 15+。
CREATE UNIQUE INDEX IF NOT EXISTS uq_folder_scope_parent_name
    ON folder (scope, parent_id, name) NULLS NOT DISTINCT
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_folder_scope_short_url
    ON folder (scope, short_url)
    WHERE deleted_at IS NULL AND short_url IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_folder_parent ON folder (parent_id);
CREATE INDEX IF NOT EXISTS idx_folder_scope ON folder (scope);

-- 既有专栏迁移为 scope='moment' 的一级文件夹。
-- 含软删记录一并迁移（保留 deleted_at），避免指向已软删专栏的手记丢失归属。
INSERT INTO folder (scope, parent_id, name, short_url, sort_order, created_at, updated_at, deleted_at)
SELECT 'moment', NULL, name, short_url, id::int, created_at, updated_at, deleted_at
FROM moment_column;

ALTER TABLE moment ADD COLUMN IF NOT EXISTS folder_id BIGINT;

UPDATE moment m
SET folder_id = f.id
FROM moment_column mc
         JOIN folder f
              ON f.name = mc.name AND f.scope = 'moment' AND f.parent_id IS NULL
WHERE m.column_id = mc.id;

ALTER TABLE moment
    ADD CONSTRAINT fk_moment_folder FOREIGN KEY (folder_id) REFERENCES folder (id);

CREATE INDEX IF NOT EXISTS idx_moment_folder_id ON moment (folder_id);

-- +goose Down

DROP INDEX IF EXISTS idx_moment_folder_id;

ALTER TABLE moment DROP CONSTRAINT IF EXISTS fk_moment_folder;
ALTER TABLE moment DROP COLUMN IF EXISTS folder_id;

DROP TABLE IF EXISTS folder;
