-- +goose Up
-- RAG tables are rebuildable derived data; moment remains the authoritative source.
-- The logical moment key intentionally survives physical source removal so withdrawal
-- can be processed durably. No foreign key or cascading delete touches core records.
CREATE TABLE rag_index_state (
    moment_id BIGINT PRIMARY KEY,
    source_hash TEXT NOT NULL,
    revision BIGINT NOT NULL DEFAULT 1,
    desired_profile TEXT NOT NULL DEFAULT '',
    active_hash TEXT,
    active_profile TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'running', 'ready', 'failed', 'excluded')),
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    lease_token TEXT,
    lease_until TIMESTAMPTZ,
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_rag_pending ON rag_index_state (next_attempt_at, moment_id)
    WHERE status IN ('pending', 'failed', 'running');

CREATE TABLE rag_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moment_id BIGINT NOT NULL REFERENCES rag_index_state(moment_id) ON DELETE RESTRICT,
    source_hash TEXT NOT NULL,
    profile TEXT NOT NULL,
    seq INTEGER NOT NULL,
    content TEXT NOT NULL,
    context_header TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL,
    start_at INTEGER NOT NULL,
    end_at INTEGER NOT NULL,
    embedding DOUBLE PRECISION[] NOT NULL,
    CONSTRAINT uq_rag_chunk UNIQUE (moment_id, seq),
    CONSTRAINT ck_rag_chunk_range CHECK (start_at >= 0 AND end_at > start_at),
    CONSTRAINT ck_rag_vector CHECK (array_ndims(embedding) = 1 AND cardinality(embedding) > 0)
);
CREATE INDEX idx_rag_chunk_profile ON rag_chunk (profile, moment_id);

-- +goose StatementBegin
CREATE FUNCTION rag_source_hash(title TEXT, summary TEXT, content TEXT, kind TEXT, short_url TEXT)
RETURNS TEXT LANGUAGE SQL IMMUTABLE PARALLEL SAFE AS $$
    SELECT md5(jsonb_build_array(title, summary, content, kind, short_url)::text)
$$;
-- +goose StatementEnd

-- Enqueue changes in the same transaction as the source write. This is independent
-- of the in-memory event bus and cannot lose updates during a process restart.
-- +goose StatementBegin
CREATE FUNCTION queue_rag_moment() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    source_id BIGINT;
    fingerprint TEXT;
    eligible BOOLEAN;
BEGIN
    IF TG_OP = 'DELETE' THEN
        source_id := OLD.id;
        fingerprint := '';
        eligible := FALSE;
    ELSE
        source_id := NEW.id;
        fingerprint := rag_source_hash(NEW.title, NEW.summary, NEW.content,
                                       NEW.ext_info->>'contentKind', NEW.short_url);
        eligible := COALESCE(NEW.is_published, FALSE) AND NEW.deleted_at IS NULL
                    AND COALESCE(NEW.ext_info->>'contentKind' IN ('article', 'note'), FALSE);
        IF TG_OP = 'UPDATE' AND fingerprint = rag_source_hash(OLD.title, OLD.summary,
            OLD.content, OLD.ext_info->>'contentKind', OLD.short_url)
            AND NEW.is_published IS NOT DISTINCT FROM OLD.is_published
            AND NEW.deleted_at IS NOT DISTINCT FROM OLD.deleted_at THEN
            RETURN NULL;
        END IF;
    END IF;
    INSERT INTO rag_index_state (moment_id, source_hash, status)
    VALUES (source_id, fingerprint, CASE WHEN eligible THEN 'pending' ELSE 'excluded' END)
    ON CONFLICT (moment_id) DO UPDATE SET
        source_hash = EXCLUDED.source_hash,
        revision = rag_index_state.revision + 1,
        status = EXCLUDED.status,
        attempts = 0,
        next_attempt_at = now(),
        lease_token = NULL,
        lease_until = NULL,
        last_error = NULL,
        updated_at = now();
    IF NOT eligible THEN
        DELETE FROM rag_chunk WHERE moment_id = source_id;
        UPDATE rag_index_state SET active_hash = NULL, active_profile = NULL WHERE moment_id = source_id;
    END IF;
    RETURN NULL;
END;
$$;
-- +goose StatementEnd
CREATE TRIGGER trg_queue_rag_moment
AFTER INSERT OR DELETE OR UPDATE OF title, summary, content, short_url, ext_info, is_published, deleted_at
ON moment FOR EACH ROW EXECUTE FUNCTION queue_rag_moment();

INSERT INTO rag_index_state (moment_id, source_hash)
SELECT id, rag_source_hash(title, summary, content, ext_info->>'contentKind', short_url)
FROM moment WHERE is_published = TRUE AND deleted_at IS NULL
    AND ext_info->>'contentKind' IN ('article', 'note');

INSERT INTO sys_config (config_key, value, is_sensitive, group_path, label, description, value_type, sort, meta)
VALUES
    ('rag.chunkSize', '1200', FALSE, 'rag', '分块字符数', '实验起点，按 Unicode 字符计数，不等同 tokenizer token', 'number', 50, '{}'::jsonb),
    ('rag.chunkOverlap', '120', FALSE, 'rag', '分块重叠字符数', '仅在同一章节内保留完整文本单元', 'number', 60, '{}'::jsonb),
    ('rag.minSimilarity', '0.35', FALSE, 'rag', '向量相似度下限', '实验起点，需要通过实际题集调整', 'string', 70, '{}'::jsonb),
    ('rag.indexVersion', '1', FALSE, 'rag', '索引版本', '模型别名背后的实际模型发生变化时递增，触发重建', 'string', 80, '{}'::jsonb)
ON CONFLICT (config_key) DO NOTHING;

-- +goose Down
-- Removes only derived RAG data and its configuration. Core content is preserved.
DROP TRIGGER trg_queue_rag_moment ON moment;
DROP FUNCTION queue_rag_moment();
DROP TABLE rag_chunk;
DROP TABLE rag_index_state;
DROP FUNCTION rag_source_hash(TEXT, TEXT, TEXT, TEXT, TEXT);
DELETE FROM sys_config WHERE config_key IN (
    'rag.chunkSize', 'rag.chunkOverlap', 'rag.minSimilarity', 'rag.indexVersion'
);
