-- +goose Up
CREATE TABLE music_favorite (
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    song_id VARCHAR(200) NOT NULL,
    snapshot JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, song_id)
);
CREATE INDEX idx_music_favorite_user_created ON music_favorite(user_id, created_at DESC, song_id);

CREATE TABLE music_playlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    name VARCHAR(100) NOT NULL CHECK (length(trim(name)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_music_playlist_owner ON music_playlist(user_id, id);

CREATE TABLE music_playlist_song (
    playlist_id BIGINT NOT NULL REFERENCES music_playlist(id) ON DELETE CASCADE,
    song_id VARCHAR(200) NOT NULL,
    sort_order INT NOT NULL CHECK (sort_order >= 0),
    snapshot JSONB NOT NULL,
    PRIMARY KEY (playlist_id, song_id)
);
CREATE INDEX idx_music_playlist_song_order ON music_playlist_song(playlist_id, sort_order, song_id);

-- +goose Down
-- Personal data must be backed up before explicitly rolling this migration back.
DROP TABLE music_playlist_song;
DROP TABLE music_playlist;
DROP TABLE music_favorite;
